###
POST http://localhost:9000/api/clientes HTTP/1.1
content-Type: application/json

{
    "nombre":"Karen Torres",
    "numeroCedula":"1045689261",
    "correo":"ktarch.h@hotmail.com"
}


###
GET http://localhost:9000/api/clientes HTTP/1.1

###
GET http://localhost:9000/api/clientes/62fce1b66e72591acb434828 HTTP/1.1

###
PUT http://localhost:9000/api/users/62fbb110f90af2e980404cab HTTP/1.1
content-Type: application/json

{
    "nombre":"Pedro Herrera",
    "numeroCedula":"123123123",
    "email":"Pedro.h@hotmail.com"
}

###
DELETE  http://localhost:9000/api/users/62f5adb3abd80ffc812768e6 HTTP/1.1

###

